--2022-08-30 13:57:46--  https://raw.githubusercontent.com/cusanovich/cmm522_code/main/test_bash.sbatch
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 287 [text/plain]
Saving to: ‘test_bash.sbatch.2’

     0K                                                       100% 16.7M=0s

2022-08-30 13:57:46 (16.7 MB/s) - ‘test_bash.sbatch.2’ saved [287/287]

